# golangci-lint v2 configuration
version: 2

run:
  timeout: 5m
  tests: true
  build-tags:
    - integration

linters:
  enable-all: true
  disable:
    - depguard # Too restrictive for dependencies
    - exhaustruct # Too noisy, requires all struct fields
    - funlen # Sometimes long functions are necessary
    - godox # We want to allow TODO/FIXME comments during development
    - wsl # Too opinionated about whitespace
    - wrapcheck # Too strict about error wrapping
    - varnamelen # Too opinionated about variable name length
    - ireturn # Sometimes returning interfaces is necessary
    - exhaustive # Can be too strict for switch statements
    - gochecknoglobals # Sometimes globals are needed
    - tagliatelle # JSON tags don't always need to match Go style
    - cyclop # Disable cyclomatic complexity checking
    - gocognit # Disable cognitive complexity checking
    - gocyclo # Disable cyclomatic complexity checking
    - nestif # Disable nested if complexity checking
    - mnd # Magic numbers are often clear in context
    - nlreturn # Too opinionated about blank lines before returns

linters-settings:
  dupl:
    threshold: 150

  errcheck:
    check-type-assertions: true
    check-blank: true

  exhaustive:
    default-signifies-exhaustive: true

  godot:
    scope: declarations

  gofumpt:
    extra-rules: true

  gosec:
    severity: medium
    confidence: medium

  govet:
    enable-all: true
    disable:
      - fieldalignment # Struct field optimization is not always necessary

  lll:
    line-length: 120

  misspell:
    locale: US

  nakedret:
    max-func-lines: 30

  nolintlint:
    require-explanation: true
    require-specific: true

  revive:
    enable-all-rules: true
    rules:
      - name: line-length-limit
        disabled: true
      - name: max-public-structs
        disabled: true
      - name: add-constant
        disabled: true
      - name: cognitive-complexity
        disabled: true
      - name: cyclomatic
        disabled: true
      - name: function-length
        disabled: true
      - name: banned-characters
        disabled: true
      - name: file-header
        disabled: true

  staticcheck:
    checks: ["all"]

  stylecheck:
    checks: ["all"]

  unused:
    check-exported: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - goconst
        - gosec
        - maintidx

    - path: test/
      linters:
        - gosec
        - goconst

    - path: cmd/
      linters:
        - gochecknoinits

    - linters:
        - staticcheck
      text: "SA1019:" # Allow deprecated for compatibility

  max-issues-per-linter: 0
  max-same-issues: 0
